name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create File
        run: echo "Olá Mundo" > arquivo.txt
        
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: arquivo
          path: '*.txt'

