name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create File
        run: echo "Olá Mundo" > arquivo.txt
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Check File
        run: ls -la

